# Generated by Django 4.2.7 on 2024-04-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuinicial', '0002_remove_funcionario_cargo_remove_funcionario_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$VGTYCXJdPYoaPeqeB7Yd46$pBRS/ADVXlqMcoM1Kp5Q9ClyTAGn5SAU5rP4jSWUZpc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
