# Generated by Django 4.2.7 on 2024-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuinicial', '0004_remove_gerente_nome_remove_gerente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kdl9bhB7k1ZXs2ER29LPsP$1Y5N8cO2wQ9fHMpe9n9jW98T+EXV1PgP3FUAW4ELV9Y=', max_length=128),
        ),
    ]
