# Generated by Django 4.2.7 on 2024-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuinicial', '0007_gerente_is_gerente_alter_funcionario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='solicitacoes_pendentes',
            field=models.ManyToManyField(blank=True, to='menuinicial.solicitacaocadastro'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$AqK9rIylYyJn7GzxAFdtP2$a0miZbIbsG0Tc5UfKzibYDVqZRhKh8wh5zstjxPAVAU=', max_length=128),
        ),
    ]
