# Generated by Django 4.2.7 on 2024-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuinicial', '0008_gerente_solicitacoes_pendentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zSqSkl2VnIxKie2ClEIIG6$IUCf5wN/ufM3sLWhfxvX6mk25ZW0nHBVYoVCS1SwmFg=', max_length=128),
        ),
    ]
